version: '3'

services:
  node:
    build: ./docker/node
    ports:
      - "4200:4200"
    volumes:
      - "./server:/projects"
    working_dir: /projects/angular-app
    command: ng serve --host 0.0.0.0
    tty: true
